//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHelperForum.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Good", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class Good : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.GoodReview[] GoodReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Goods_CatergoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Goods_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Goods_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Goods_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Goods_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Goods_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ProductCart[] ProductCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Student_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.GoodReview[] GoodReviews {
            get {
                return this.GoodReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodReviewsField, value) != true)) {
                    this.GoodReviewsField = value;
                    this.RaisePropertyChanged("GoodReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Goods_Catergory {
            get {
                return this.Goods_CatergoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Goods_CatergoryField, value) != true)) {
                    this.Goods_CatergoryField = value;
                    this.RaisePropertyChanged("Goods_Catergory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Goods_Description {
            get {
                return this.Goods_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Goods_DescriptionField, value) != true)) {
                    this.Goods_DescriptionField = value;
                    this.RaisePropertyChanged("Goods_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Goods_ID {
            get {
                return this.Goods_IDField;
            }
            set {
                if ((this.Goods_IDField.Equals(value) != true)) {
                    this.Goods_IDField = value;
                    this.RaisePropertyChanged("Goods_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Goods_Image {
            get {
                return this.Goods_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Goods_ImageField, value) != true)) {
                    this.Goods_ImageField = value;
                    this.RaisePropertyChanged("Goods_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Goods_Name {
            get {
                return this.Goods_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Goods_NameField, value) != true)) {
                    this.Goods_NameField = value;
                    this.RaisePropertyChanged("Goods_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Goods_Price {
            get {
                return this.Goods_PriceField;
            }
            set {
                if ((this.Goods_PriceField.Equals(value) != true)) {
                    this.Goods_PriceField = value;
                    this.RaisePropertyChanged("Goods_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ProductCart[] ProductCarts {
            get {
                return this.ProductCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCartsField, value) != true)) {
                    this.ProductCartsField = value;
                    this.RaisePropertyChanged("ProductCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_Number {
            get {
                return this.Student_NumberField;
            }
            set {
                if ((this.Student_NumberField.Equals(value) != true)) {
                    this.Student_NumberField = value;
                    this.RaisePropertyChanged("Student_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.GoodReview[] GoodReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Good[] GoodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ProductCart[] ProductCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ServiceCart[] ServiceCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ServiceReview[] ServiceReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Service[] ServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Student_Cellphone_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Student_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_Personal_EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Student_UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.GoodReview[] GoodReviews {
            get {
                return this.GoodReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodReviewsField, value) != true)) {
                    this.GoodReviewsField = value;
                    this.RaisePropertyChanged("GoodReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Good[] Goods {
            get {
                return this.GoodsField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsField, value) != true)) {
                    this.GoodsField = value;
                    this.RaisePropertyChanged("Goods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ProductCart[] ProductCarts {
            get {
                return this.ProductCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCartsField, value) != true)) {
                    this.ProductCartsField = value;
                    this.RaisePropertyChanged("ProductCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ServiceCart[] ServiceCarts {
            get {
                return this.ServiceCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCartsField, value) != true)) {
                    this.ServiceCartsField = value;
                    this.RaisePropertyChanged("ServiceCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ServiceReview[] ServiceReviews {
            get {
                return this.ServiceReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceReviewsField, value) != true)) {
                    this.ServiceReviewsField = value;
                    this.RaisePropertyChanged("ServiceReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Service[] Services {
            get {
                return this.ServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicesField, value) != true)) {
                    this.ServicesField = value;
                    this.RaisePropertyChanged("Services");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Address {
            get {
                return this.Student_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_AddressField, value) != true)) {
                    this.Student_AddressField = value;
                    this.RaisePropertyChanged("Student_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_Cellphone_Number {
            get {
                return this.Student_Cellphone_NumberField;
            }
            set {
                if ((this.Student_Cellphone_NumberField.Equals(value) != true)) {
                    this.Student_Cellphone_NumberField = value;
                    this.RaisePropertyChanged("Student_Cellphone_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Email {
            get {
                return this.Student_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_EmailField, value) != true)) {
                    this.Student_EmailField = value;
                    this.RaisePropertyChanged("Student_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Name {
            get {
                return this.Student_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_NameField, value) != true)) {
                    this.Student_NameField = value;
                    this.RaisePropertyChanged("Student_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_Number {
            get {
                return this.Student_NumberField;
            }
            set {
                if ((this.Student_NumberField.Equals(value) != true)) {
                    this.Student_NumberField = value;
                    this.RaisePropertyChanged("Student_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Personal_Email {
            get {
                return this.Student_Personal_EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_Personal_EmailField, value) != true)) {
                    this.Student_Personal_EmailField = value;
                    this.RaisePropertyChanged("Student_Personal_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Surname {
            get {
                return this.Student_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_SurnameField, value) != true)) {
                    this.Student_SurnameField = value;
                    this.RaisePropertyChanged("Student_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student_Username {
            get {
                return this.Student_UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.Student_UsernameField, value) != true)) {
                    this.Student_UsernameField = value;
                    this.RaisePropertyChanged("Student_Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodReview", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class GoodReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Good GoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int reviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sNUMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Good Good {
            get {
                return this.GoodField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodField, value) != true)) {
                    this.GoodField = value;
                    this.RaisePropertyChanged("Good");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gID {
            get {
                return this.gIDField;
            }
            set {
                if ((this.gIDField.Equals(value) != true)) {
                    this.gIDField = value;
                    this.RaisePropertyChanged("gID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reviewID {
            get {
                return this.reviewIDField;
            }
            set {
                if ((this.reviewIDField.Equals(value) != true)) {
                    this.reviewIDField = value;
                    this.RaisePropertyChanged("reviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sNUM {
            get {
                return this.sNUMField;
            }
            set {
                if ((this.sNUMField.Equals(value) != true)) {
                    this.sNUMField = value;
                    this.RaisePropertyChanged("sNUM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCart", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class ProductCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Good GoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sNUMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Good Good {
            get {
                return this.GoodField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodField, value) != true)) {
                    this.GoodField = value;
                    this.RaisePropertyChanged("Good");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemQuantity {
            get {
                return this.ItemQuantityField;
            }
            set {
                if ((this.ItemQuantityField.Equals(value) != true)) {
                    this.ItemQuantityField = value;
                    this.RaisePropertyChanged("ItemQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sNUM {
            get {
                return this.sNUMField;
            }
            set {
                if ((this.sNUMField.Equals(value) != true)) {
                    this.sNUMField = value;
                    this.RaisePropertyChanged("sNUM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCart", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class ServiceCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Service ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sNUMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemQuantity {
            get {
                return this.ItemQuantityField;
            }
            set {
                if ((this.ItemQuantityField.Equals(value) != true)) {
                    this.ItemQuantityField = value;
                    this.RaisePropertyChanged("ItemQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Service Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceID {
            get {
                return this.ServiceIDField;
            }
            set {
                if ((this.ServiceIDField.Equals(value) != true)) {
                    this.ServiceIDField = value;
                    this.RaisePropertyChanged("ServiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sNUM {
            get {
                return this.sNUMField;
            }
            set {
                if ((this.sNUMField.Equals(value) != true)) {
                    this.sNUMField = value;
                    this.RaisePropertyChanged("sNUM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceReview", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class ServiceReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Service ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int reviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sNUMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Service Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reviewID {
            get {
                return this.reviewIDField;
            }
            set {
                if ((this.reviewIDField.Equals(value) != true)) {
                    this.reviewIDField = value;
                    this.RaisePropertyChanged("reviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sID {
            get {
                return this.sIDField;
            }
            set {
                if ((this.sIDField.Equals(value) != true)) {
                    this.sIDField = value;
                    this.RaisePropertyChanged("sID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sNUM {
            get {
                return this.sNUMField;
            }
            set {
                if ((this.sNUMField.Equals(value) != true)) {
                    this.sNUMField = value;
                    this.RaisePropertyChanged("sNUM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/Akatsuki_Service")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ServiceCart[] ServiceCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.ServiceReview[] ServiceReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Services_CatergoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Services_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Services_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Services_Image_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Services_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Services_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentHelperForum.ServiceReference1.Student StudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Student_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ServiceCart[] ServiceCarts {
            get {
                return this.ServiceCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCartsField, value) != true)) {
                    this.ServiceCartsField = value;
                    this.RaisePropertyChanged("ServiceCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.ServiceReview[] ServiceReviews {
            get {
                return this.ServiceReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceReviewsField, value) != true)) {
                    this.ServiceReviewsField = value;
                    this.RaisePropertyChanged("ServiceReviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Services_Catergory {
            get {
                return this.Services_CatergoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Services_CatergoryField, value) != true)) {
                    this.Services_CatergoryField = value;
                    this.RaisePropertyChanged("Services_Catergory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Services_Description {
            get {
                return this.Services_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Services_DescriptionField, value) != true)) {
                    this.Services_DescriptionField = value;
                    this.RaisePropertyChanged("Services_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Services_ID {
            get {
                return this.Services_IDField;
            }
            set {
                if ((this.Services_IDField.Equals(value) != true)) {
                    this.Services_IDField = value;
                    this.RaisePropertyChanged("Services_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Services_Image_ {
            get {
                return this.Services_Image_Field;
            }
            set {
                if ((object.ReferenceEquals(this.Services_Image_Field, value) != true)) {
                    this.Services_Image_Field = value;
                    this.RaisePropertyChanged("Services_Image_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Services_Name {
            get {
                return this.Services_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Services_NameField, value) != true)) {
                    this.Services_NameField = value;
                    this.RaisePropertyChanged("Services_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Services_Price {
            get {
                return this.Services_PriceField;
            }
            set {
                if ((this.Services_PriceField.Equals(value) != true)) {
                    this.Services_PriceField = value;
                    this.RaisePropertyChanged("Services_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentHelperForum.ServiceReference1.Student Student {
            get {
                return this.StudentField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentField, value) != true)) {
                    this.StudentField = value;
                    this.RaisePropertyChanged("Student");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Student_Number {
            get {
                return this.Student_NumberField;
            }
            set {
                if ((this.Student_NumberField.Equals(value) != true)) {
                    this.Student_NumberField = value;
                    this.RaisePropertyChanged("Student_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        bool SignUp(int sNum, string sAddress, string sEmail, string personalEmail, int cellphoneNum, string fName, string lName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignUp", ReplyAction="http://tempuri.org/IService1/SignUpResponse")]
        System.Threading.Tasks.Task<bool> SignUpAsync(int sNum, string sAddress, string sEmail, string personalEmail, int cellphoneNum, string fName, string lName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_To_Cart_Service", ReplyAction="http://tempuri.org/IService1/Add_To_Cart_ServiceResponse")]
        bool Add_To_Cart_Service(int sNUm, int ServiceID, int ItemQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_To_Cart_Service", ReplyAction="http://tempuri.org/IService1/Add_To_Cart_ServiceResponse")]
        System.Threading.Tasks.Task<bool> Add_To_Cart_ServiceAsync(int sNUm, int ServiceID, int ItemQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_To_Cart_Product", ReplyAction="http://tempuri.org/IService1/Add_To_Cart_ProductResponse")]
        bool Add_To_Cart_Product(int sNUm, int ProductID, int ItemQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add_To_Cart_Product", ReplyAction="http://tempuri.org/IService1/Add_To_Cart_ProductResponse")]
        System.Threading.Tasks.Task<bool> Add_To_Cart_ProductAsync(int sNUm, int ProductID, int ItemQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteGoodCart", ReplyAction="http://tempuri.org/IService1/deleteGoodCartResponse")]
        bool deleteGoodCart(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteGoodCart", ReplyAction="http://tempuri.org/IService1/deleteGoodCartResponse")]
        System.Threading.Tasks.Task<bool> deleteGoodCartAsync(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteServiceCart", ReplyAction="http://tempuri.org/IService1/deleteServiceCartResponse")]
        bool deleteServiceCart(int ServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteServiceCart", ReplyAction="http://tempuri.org/IService1/deleteServiceCartResponse")]
        System.Threading.Tasks.Task<bool> deleteServiceCartAsync(int ServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignIn", ReplyAction="http://tempuri.org/IService1/SignInResponse")]
        string SignIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignIn", ReplyAction="http://tempuri.org/IService1/SignInResponse")]
        System.Threading.Tasks.Task<string> SignInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodsList", ReplyAction="http://tempuri.org/IService1/getGoodsListResponse")]
        StudentHelperForum.ServiceReference1.Good[] getGoodsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodsList", ReplyAction="http://tempuri.org/IService1/getGoodsListResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Good[]> getGoodsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodItem", ReplyAction="http://tempuri.org/IService1/getGoodItemResponse")]
        StudentHelperForum.ServiceReference1.Good getGoodItem(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodItem", ReplyAction="http://tempuri.org/IService1/getGoodItemResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Good> getGoodItemAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServicesList", ReplyAction="http://tempuri.org/IService1/getServicesListResponse")]
        StudentHelperForum.ServiceReference1.Service[] getServicesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServicesList", ReplyAction="http://tempuri.org/IService1/getServicesListResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Service[]> getServicesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductCartList", ReplyAction="http://tempuri.org/IService1/getProductCartListResponse")]
        StudentHelperForum.ServiceReference1.ProductCart[] getProductCartList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductCartList", ReplyAction="http://tempuri.org/IService1/getProductCartListResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ProductCart[]> getProductCartListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceCartList", ReplyAction="http://tempuri.org/IService1/getServiceCartListResponse")]
        StudentHelperForum.ServiceReference1.ServiceCart[] getServiceCartList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceCartList", ReplyAction="http://tempuri.org/IService1/getServiceCartListResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceCart[]> getServiceCartListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceItem", ReplyAction="http://tempuri.org/IService1/getServiceItemResponse")]
        StudentHelperForum.ServiceReference1.Service getServiceItem(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceItem", ReplyAction="http://tempuri.org/IService1/getServiceItemResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Service> getServiceItemAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addGood", ReplyAction="http://tempuri.org/IService1/addGoodResponse")]
        bool addGood(int studentNum, string gName, decimal gPrice, string gdescription, string gImage, string gcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addGood", ReplyAction="http://tempuri.org/IService1/addGoodResponse")]
        System.Threading.Tasks.Task<bool> addGoodAsync(int studentNum, string gName, decimal gPrice, string gdescription, string gImage, string gcategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteGood", ReplyAction="http://tempuri.org/IService1/deleteGoodResponse")]
        bool deleteGood(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteGood", ReplyAction="http://tempuri.org/IService1/deleteGoodResponse")]
        System.Threading.Tasks.Task<bool> deleteGoodAsync(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addService", ReplyAction="http://tempuri.org/IService1/addServiceResponse")]
        bool addService(int studentNum, string sName, decimal sPrice, string sdescription, string sImage, string scategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addService", ReplyAction="http://tempuri.org/IService1/addServiceResponse")]
        System.Threading.Tasks.Task<bool> addServiceAsync(int studentNum, string sName, decimal sPrice, string sdescription, string sImage, string scategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteService", ReplyAction="http://tempuri.org/IService1/deleteServiceResponse")]
        bool deleteService(int serviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteService", ReplyAction="http://tempuri.org/IService1/deleteServiceResponse")]
        System.Threading.Tasks.Task<bool> deleteServiceAsync(int serviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceReviews", ReplyAction="http://tempuri.org/IService1/getServiceReviewsResponse")]
        StudentHelperForum.ServiceReference1.ServiceReview[] getServiceReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceReviews", ReplyAction="http://tempuri.org/IService1/getServiceReviewsResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceReview[]> getServiceReviewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodReviews", ReplyAction="http://tempuri.org/IService1/getGoodReviewsResponse")]
        StudentHelperForum.ServiceReference1.GoodReview[] getGoodReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodReviews", ReplyAction="http://tempuri.org/IService1/getGoodReviewsResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.GoodReview[]> getGoodReviewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodReview", ReplyAction="http://tempuri.org/IService1/getGoodReviewResponse")]
        StudentHelperForum.ServiceReference1.GoodReview getGoodReview(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGoodReview", ReplyAction="http://tempuri.org/IService1/getGoodReviewResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.GoodReview> getGoodReviewAsync(int goodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceReview", ReplyAction="http://tempuri.org/IService1/getServiceReviewResponse")]
        StudentHelperForum.ServiceReference1.ServiceReview getServiceReview(int serviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getServiceReview", ReplyAction="http://tempuri.org/IService1/getServiceReviewResponse")]
        System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceReview> getServiceReviewAsync(int serviceID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : StudentHelperForum.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<StudentHelperForum.ServiceReference1.IService1>, StudentHelperForum.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SignUp(int sNum, string sAddress, string sEmail, string personalEmail, int cellphoneNum, string fName, string lName, string password) {
            return base.Channel.SignUp(sNum, sAddress, sEmail, personalEmail, cellphoneNum, fName, lName, password);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(int sNum, string sAddress, string sEmail, string personalEmail, int cellphoneNum, string fName, string lName, string password) {
            return base.Channel.SignUpAsync(sNum, sAddress, sEmail, personalEmail, cellphoneNum, fName, lName, password);
        }
        
        public bool Add_To_Cart_Service(int sNUm, int ServiceID, int ItemQuantity) {
            return base.Channel.Add_To_Cart_Service(sNUm, ServiceID, ItemQuantity);
        }
        
        public System.Threading.Tasks.Task<bool> Add_To_Cart_ServiceAsync(int sNUm, int ServiceID, int ItemQuantity) {
            return base.Channel.Add_To_Cart_ServiceAsync(sNUm, ServiceID, ItemQuantity);
        }
        
        public bool Add_To_Cart_Product(int sNUm, int ProductID, int ItemQuantity) {
            return base.Channel.Add_To_Cart_Product(sNUm, ProductID, ItemQuantity);
        }
        
        public System.Threading.Tasks.Task<bool> Add_To_Cart_ProductAsync(int sNUm, int ProductID, int ItemQuantity) {
            return base.Channel.Add_To_Cart_ProductAsync(sNUm, ProductID, ItemQuantity);
        }
        
        public bool deleteGoodCart(int goodID) {
            return base.Channel.deleteGoodCart(goodID);
        }
        
        public System.Threading.Tasks.Task<bool> deleteGoodCartAsync(int goodID) {
            return base.Channel.deleteGoodCartAsync(goodID);
        }
        
        public bool deleteServiceCart(int ServiceID) {
            return base.Channel.deleteServiceCart(ServiceID);
        }
        
        public System.Threading.Tasks.Task<bool> deleteServiceCartAsync(int ServiceID) {
            return base.Channel.deleteServiceCartAsync(ServiceID);
        }
        
        public string SignIn(string email, string password) {
            return base.Channel.SignIn(email, password);
        }
        
        public System.Threading.Tasks.Task<string> SignInAsync(string email, string password) {
            return base.Channel.SignInAsync(email, password);
        }
        
        public StudentHelperForum.ServiceReference1.Good[] getGoodsList() {
            return base.Channel.getGoodsList();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Good[]> getGoodsListAsync() {
            return base.Channel.getGoodsListAsync();
        }
        
        public StudentHelperForum.ServiceReference1.Good getGoodItem(int ID) {
            return base.Channel.getGoodItem(ID);
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Good> getGoodItemAsync(int ID) {
            return base.Channel.getGoodItemAsync(ID);
        }
        
        public StudentHelperForum.ServiceReference1.Service[] getServicesList() {
            return base.Channel.getServicesList();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Service[]> getServicesListAsync() {
            return base.Channel.getServicesListAsync();
        }
        
        public StudentHelperForum.ServiceReference1.ProductCart[] getProductCartList() {
            return base.Channel.getProductCartList();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ProductCart[]> getProductCartListAsync() {
            return base.Channel.getProductCartListAsync();
        }
        
        public StudentHelperForum.ServiceReference1.ServiceCart[] getServiceCartList() {
            return base.Channel.getServiceCartList();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceCart[]> getServiceCartListAsync() {
            return base.Channel.getServiceCartListAsync();
        }
        
        public StudentHelperForum.ServiceReference1.Service getServiceItem(int ID) {
            return base.Channel.getServiceItem(ID);
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.Service> getServiceItemAsync(int ID) {
            return base.Channel.getServiceItemAsync(ID);
        }
        
        public bool addGood(int studentNum, string gName, decimal gPrice, string gdescription, string gImage, string gcategory) {
            return base.Channel.addGood(studentNum, gName, gPrice, gdescription, gImage, gcategory);
        }
        
        public System.Threading.Tasks.Task<bool> addGoodAsync(int studentNum, string gName, decimal gPrice, string gdescription, string gImage, string gcategory) {
            return base.Channel.addGoodAsync(studentNum, gName, gPrice, gdescription, gImage, gcategory);
        }
        
        public bool deleteGood(int goodID) {
            return base.Channel.deleteGood(goodID);
        }
        
        public System.Threading.Tasks.Task<bool> deleteGoodAsync(int goodID) {
            return base.Channel.deleteGoodAsync(goodID);
        }
        
        public bool addService(int studentNum, string sName, decimal sPrice, string sdescription, string sImage, string scategory) {
            return base.Channel.addService(studentNum, sName, sPrice, sdescription, sImage, scategory);
        }
        
        public System.Threading.Tasks.Task<bool> addServiceAsync(int studentNum, string sName, decimal sPrice, string sdescription, string sImage, string scategory) {
            return base.Channel.addServiceAsync(studentNum, sName, sPrice, sdescription, sImage, scategory);
        }
        
        public bool deleteService(int serviceID) {
            return base.Channel.deleteService(serviceID);
        }
        
        public System.Threading.Tasks.Task<bool> deleteServiceAsync(int serviceID) {
            return base.Channel.deleteServiceAsync(serviceID);
        }
        
        public StudentHelperForum.ServiceReference1.ServiceReview[] getServiceReviews() {
            return base.Channel.getServiceReviews();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceReview[]> getServiceReviewsAsync() {
            return base.Channel.getServiceReviewsAsync();
        }
        
        public StudentHelperForum.ServiceReference1.GoodReview[] getGoodReviews() {
            return base.Channel.getGoodReviews();
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.GoodReview[]> getGoodReviewsAsync() {
            return base.Channel.getGoodReviewsAsync();
        }
        
        public StudentHelperForum.ServiceReference1.GoodReview getGoodReview(int goodID) {
            return base.Channel.getGoodReview(goodID);
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.GoodReview> getGoodReviewAsync(int goodID) {
            return base.Channel.getGoodReviewAsync(goodID);
        }
        
        public StudentHelperForum.ServiceReference1.ServiceReview getServiceReview(int serviceID) {
            return base.Channel.getServiceReview(serviceID);
        }
        
        public System.Threading.Tasks.Task<StudentHelperForum.ServiceReference1.ServiceReview> getServiceReviewAsync(int serviceID) {
            return base.Channel.getServiceReviewAsync(serviceID);
        }
    }
}
